relative-paths: true
models:
- model.enzh.intgemm.alphas.bin
vocabs:
- vocab.enzh.spm
- vocab.enzh.spm
shortlist:
- lex.50.50.enzh.s2t.bin
- false
beam-size: 1
normalize: 1.0
word-penalty: 0
max-length-break: 128
mini-batch-words: 1024
workspace: 128
max-length-factor: 2.0
skip-cost: true
cpu-threads: 0
quiet: true
quiet-translation: true
gemm-precision: int8shiftAlphaAll